name: Run Test
on:
  push:
    branches-ignore:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Cypress Test Action
        uses: ./.github/actions/cypress-test
        with:
          cypress-project-id: ${{ secrets.NEXT_PUBLIC_CYPRESS_ID }}
          cypress-record-key: ${{ secrets.CYPRESS_RECORD_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
